import { useEffect, useMemo, useRef, useState } from 'react'
import { Bell, CalendarDays, Check, ChevronRight, Download, Heart, Home, Import, Lightbulb, Menu, Moon, MoreHorizontal, Pencil, Plus, RotateCcw, Search, Settings as SettingsIcon, Sparkles, Sun, Trash2, UserRound, Users, X } from 'lucide-react'
import { relationships, seedPeople, seedReminders, starters, suggestionBank } from './data'

const KEY='nudgeai-v2-data'
const initial={people:seedPeople,reminders:seedReminders,dark:false,notifications:false,firstName:'Alex'}
const today=()=>new Date().toISOString().slice(0,10)
const uid=()=>crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`
const formatDate=(date)=>date ? new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}) : 'Not set'
const daysUntil=(date)=>{if(!date)return null;const now=new Date();const target=new Date(now.getFullYear(),Number(date.slice(5,7))-1,Number(date.slice(8,10)));if(target<new Date(now.getFullYear(),now.getMonth(),now.getDate()))target.setFullYear(now.getFullYear()+1);return Math.ceil((target-now)/86400000)}

function Avatar({person,size='md'}){return <span className={`avatar ${person?.color||'teal'} ${size}`}>{person?.name?.[0]?.toUpperCase()||'?'}</span>}
function Empty({icon:Icon,title,copy,action,label}){return <div className="empty"><span className="empty-icon"><Icon/></span><h3>{title}</h3><p>{copy}</p>{action&&<button className="primary" onClick={action}><Plus size={17}/>{label}</button>}</div>}
function Modal({title,onClose,children}){useEffect(()=>{const f=e=>e.key==='Escape'&&onClose();addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[onClose]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close"><X/></button></div>{children}</section></div>}

function PersonForm({person,onSave,onClose}){const [form,setForm]=useState(person||{name:'',relationship:'Partner',birthday:'',anniversary:'',notes:'',color:'teal'});const [error,setError]=useState('');const change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=e=>{e.preventDefault();if(!form.name.trim()){setError('Please enter a name.');return}onSave({...form,name:form.name.trim(),id:form.id||uid()})};return <form onSubmit={submit} className="form"><label>Name *<input autoFocus name="name" value={form.name} onChange={change} placeholder="Who do you want to appreciate?"/>{error&&<small className="error">{error}</small>}</label><label>Relationship<select name="relationship" value={form.relationship} onChange={change}>{relationships.map(x=><option key={x}>{x}</option>)}</select></label><div className="form-row"><label>Birthday<input type="date" name="birthday" value={form.birthday} onChange={change}/></label><label>Anniversary<input type="date" name="anniversary" value={form.anniversary} onChange={change}/></label></div><label>Notes<textarea name="notes" value={form.notes} onChange={change} placeholder="Favorites, things to ask about…" rows="3"/></label><fieldset><legend>Color</legend><div className="color-picker">{['teal','coral','amber','olive','charcoal'].map(c=><button type="button" aria-label={c} className={`swatch ${c} ${form.color===c?'selected':''}`} onClick={()=>setForm({...form,color:c})} key={c}/>)}</div></fieldset><div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Save person</button></div></form>}

function ReminderForm({people,prefill,onSave,onClose}){const [form,setForm]=useState({title:prefill?.title||'',personId:prefill?.personId||people[0]?.id||'',date:prefill?.date||today(),time:prefill?.time||'09:00',repeat:prefill?.repeat||'Never'});const [error,setError]=useState('');const change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=e=>{e.preventDefault();if(!form.title.trim())return setError('Add a short reminder.');if(!form.date)return setError('Choose a date.');onSave({...form,title:form.title.trim(),id:prefill?.id||uid(),done:prefill?.done||false})};return <form className="form" onSubmit={submit}><label>Reminder *<input autoFocus name="title" value={form.title} onChange={change} placeholder="Send a thoughtful message"/>{error&&<small className="error">{error}</small>}</label><label>For<select name="personId" value={form.personId} onChange={change}><option value="">Anyone</option>{people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="form-row"><label>Date<input type="date" name="date" value={form.date} onChange={change}/></label><label>Time<input type="time" name="time" value={form.time} onChange={change}/></label></div><label>Repeat<select name="repeat" value={form.repeat} onChange={change}>{['Never','Daily','Weekly','Monthly','Yearly'].map(x=><option key={x}>{x}</option>)}</select></label><div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Save reminder</button></div></form>}

export default function App(){
 const [data,setData]=useState(()=>{try{return {...initial,...JSON.parse(localStorage.getItem(KEY))}}catch{return initial}});const [page,setPage]=useState('Home');const [modal,setModal]=useState(null);const [toast,setToast]=useState('');const importRef=useRef();
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(data));document.documentElement.dataset.theme=data.dark?'dark':'light'},[data]);
 useEffect(()=>{const due=data.reminders.filter(r=>!r.done&&`${r.date}T${r.time||'00:00'}`<=new Date().toISOString().slice(0,16));if(data.notifications&&Notification.permission==='granted'&&due.length&&sessionStorage.getItem('notified')!==today()){new Notification('A gentle NudgeAI reminder',{body:`You have ${due.length} thoughtful nudge${due.length>1?'s':''} waiting.`});sessionStorage.setItem('notified',today())}},[data.notifications,data.reminders]);
 const showToast=t=>{setToast(t);setTimeout(()=>setToast(''),2600)};const savePerson=p=>{setData(d=>({...d,people:d.people.some(x=>x.id===p.id)?d.people.map(x=>x.id===p.id?p:x):[...d.people,p]}));setModal(null);showToast('Person saved')};
 const deletePerson=id=>{if(confirm('Delete this person and their reminders?')){setData(d=>({...d,people:d.people.filter(p=>p.id!==id),reminders:d.reminders.filter(r=>r.personId!==id)}));showToast('Person deleted')}};
 const saveReminder=r=>{setData(d=>({...d,reminders:d.reminders.some(x=>x.id===r.id)?d.reminders.map(x=>x.id===r.id?r:x):[...d.reminders,r]}));setModal(null);showToast('Reminder saved')};
 const toggleReminder=id=>setData(d=>({...d,reminders:d.reminders.map(r=>r.id===id?{...r,done:!r.done}:r)}));const deleteReminder=id=>setData(d=>({...d,reminders:d.reminders.filter(r=>r.id!==id)}));
 const nav=[['Home',Home],['People',Users],['Ideas',Lightbulb],['Reminders',Bell],['Settings',SettingsIcon]];
 const notify=async()=>{if(!('Notification'in window))return showToast('Notifications are not supported here');const permission=await Notification.requestPermission();setData(d=>({...d,notifications:permission==='granted'}));showToast(permission==='granted'?'Notifications enabled':'Notification permission not granted')};
 const exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nudgeai-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href);showToast('Backup downloaded')};
 const importData=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const x=JSON.parse(reader.result);if(!Array.isArray(x.people)||!Array.isArray(x.reminders))throw Error();setData({...initial,...x});showToast('Backup restored')}catch{showToast('That backup file is not valid')}};reader.readAsText(file);e.target.value=''};
 return <div className="app"><aside className="sidebar"><button className="brand" onClick={()=>setPage('Home')}><span><Heart fill="currentColor"/></span>NudgeAI</button><p className="tagline">Love, remembered.</p><nav>{nav.map(([label,Icon])=><button className={page===label?'active':''} onClick={()=>setPage(label)} key={label}><Icon/>{label}</button>)}</nav><div className="sidebar-card"><Sparkles/><strong>Small moments matter</strong><p>One thoughtful nudge can change someone’s whole day.</p></div><button className="profile"><span className="mini-avatar">{data.firstName[0]}</span><span><strong>{data.firstName}</strong><small>Your private space</small></span><MoreHorizontal/></button></aside>
 <main><header><div><p className="eyebrow">{page==='Home'?new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}):'NudgeAI'}</p><h1>{page==='Home'?`Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, ${data.firstName}`:page}</h1></div><div className="header-actions"><button className="icon-button" onClick={()=>setData(d=>({...d,dark:!d.dark}))} aria-label="Toggle dark mode">{data.dark?<Sun/>:<Moon/>}</button>{page!=='Settings'&&<button className="primary" onClick={()=>setModal(page==='People'?'person':'reminder')}><Plus/> {page==='People'?'Add person':'New reminder'}</button>}</div></header>
 {page==='Home'&&<Dashboard data={data} setPage={setPage} setModal={setModal} toggle={toggleReminder}/>} {page==='People'&&<People people={data.people} edit={p=>setModal({type:'person',value:p})} remove={deletePerson} add={()=>setModal('person')}/>} {page==='Ideas'&&<Ideas people={data.people} remind={(title,personId)=>setModal({type:'reminder',value:{title,personId}})}/>} {page==='Reminders'&&<Reminders reminders={data.reminders} people={data.people} toggle={toggleReminder} remove={deleteReminder} edit={r=>setModal({type:'reminder',value:r})} add={()=>setModal('reminder')}/>} {page==='Settings'&&<Settings data={data} setData={setData} notify={notify} exportData={exportData} importRef={importRef} importData={importData}/>} 
 </main><nav className="mobile-nav">{nav.map(([label,Icon])=><button className={page===label?'active':''} onClick={()=>setPage(label)} key={label}><Icon/><span>{label}</span></button>)}</nav>
 {(modal==='person'||modal?.type==='person')&&<Modal title={modal?.value?'Edit person':'Add someone special'} onClose={()=>setModal(null)}><PersonForm person={modal?.value} onSave={savePerson} onClose={()=>setModal(null)}/></Modal>}{(modal==='reminder'||modal?.type==='reminder')&&<Modal title={modal?.value?.id?'Edit reminder':'Create a reminder'} onClose={()=>setModal(null)}><ReminderForm people={data.people} prefill={modal?.value} onSave={saveReminder} onClose={()=>setModal(null)}/></Modal>}{toast&&<div className="toast"><Check/>{toast}</div>}</div>
}

function Dashboard({data,setPage,setModal,toggle}){const upcoming=[...data.reminders].filter(r=>!r.done).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4);const dates=data.people.flatMap(p=>[['Birthday',p.birthday],['Anniversary',p.anniversary]].filter(x=>x[1]).map(([kind,date])=>({p,kind,date,days:daysUntil(date)}))).sort((a,b)=>a.days-b.days).slice(0,3);const featured=data.people[0];return <div className="page dashboard"><section className="hero-card"><div><span className="pill"><Sparkles/> TODAY’S NUDGE</span><h2>{featured?`Make ${featured.name} feel seen today.`:'Start with someone who matters.'}</h2><p>{featured?suggestionBank[featured.relationship][0]:'Add a person and NudgeAI will offer thoughtful, personal ideas.'}</p><div className="hero-actions">{featured?<><button className="primary light" onClick={()=>setModal({type:'reminder',value:{personId:featured.id,title:suggestionBank[featured.relationship][0]}})}>Remind me <ChevronRight/></button><button className="text-button" onClick={()=>setPage('Ideas')}>See another idea</button></>:<button className="primary light" onClick={()=>setModal('person')}>Add your first person</button>}</div></div><Heart className="hero-heart" fill="currentColor"/></section><div className="stats"><article><span className="stat-icon coral"><Users/></span><div><strong>{data.people.length}</strong><small>People you care for</small></div></article><article><span className="stat-icon amber"><Bell/></span><div><strong>{upcoming.length}</strong><small>Upcoming nudges</small></div></article><article><span className="stat-icon olive"><Check/></span><div><strong>{data.reminders.filter(r=>r.done).length}</strong><small>Kind moments done</small></div></article></div><div className="two-col"><section className="panel"><div className="section-head"><div><p className="eyebrow">STAY INTENTIONAL</p><h2>Coming up</h2></div><button className="text-button" onClick={()=>setPage('Reminders')}>View all</button></div>{upcoming.length?upcoming.map(r=><ReminderRow key={r.id} r={r} person={data.people.find(p=>p.id===r.personId)} toggle={toggle}/>):<Empty icon={Bell} title="A clear horizon" copy="Create a reminder for your next thoughtful moment." action={()=>setModal('reminder')} label="Add reminder"/>}</section><section className="panel"><div className="section-head"><div><p className="eyebrow">CELEBRATE THEM</p><h2>Special dates</h2></div></div>{dates.length?dates.map(x=><div className="date-row" key={x.p.id+x.kind}><Avatar person={x.p}/><div><strong>{x.p.name}’s {x.kind.toLowerCase()}</strong><small>{formatDate(x.date)}</small></div><span className="day-badge">{x.days===0?'Today':`${x.days}d`}</span></div>):<Empty icon={CalendarDays} title="No dates yet" copy="Add birthdays and anniversaries to never miss a celebration."/>}</section></div></div>}
function ReminderRow({r,person,toggle,remove,edit}){return <div className={`reminder-row ${r.done?'done':''}`}><button className="check" onClick={()=>toggle(r.id)} aria-label={r.done?'Mark incomplete':'Complete reminder'}>{r.done&&<Check/>}</button><div className="reminder-main"><strong>{r.title}</strong><small>{person?.name||'General'} · {formatDate(r.date)} at {r.time}</small></div>{person&&<Avatar person={person} size="sm"/>}{edit&&<button className="icon-button tiny" onClick={()=>edit(r)} aria-label="Edit"><Pencil/></button>}{remove&&<button className="icon-button tiny danger" onClick={()=>remove(r.id)} aria-label="Delete"><Trash2/></button>}</div>}
function People({people,edit,remove,add}){const [q,setQ]=useState('');const filtered=people.filter(p=>`${p.name} ${p.relationship}`.toLowerCase().includes(q.toLowerCase()));return <div className="page"><div className="toolbar"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search people…"/></div><span>{filtered.length} {filtered.length===1?'person':'people'}</span></div>{filtered.length?<div className="people-grid">{filtered.map(p=><article className="person-card" key={p.id}><div className="person-top"><Avatar person={p} size="lg"/><div className="card-actions"><button className="icon-button tiny" onClick={()=>edit(p)} aria-label={`Edit ${p.name}`}><Pencil/></button><button className="icon-button tiny danger" onClick={()=>remove(p.id)} aria-label={`Delete ${p.name}`}><Trash2/></button></div></div><h2>{p.name}</h2><span className="relationship">{p.relationship}</span>{p.notes&&<p>{p.notes}</p>}<div className="dates"><small><CalendarDays/> Birthday: {formatDate(p.birthday)}</small><small><Heart/> Anniversary: {formatDate(p.anniversary)}</small></div></article>)}</div>:<Empty icon={UserRound} title={q?'No matches found':'Your circle starts here'} copy={q?'Try a different name or relationship.':'Add the people you want to encourage more intentionally.'} action={!q&&add} label="Add a person"/>}</div>}
function Ideas({people,remind}){const [filter,setFilter]=useState('All');const [starter,setStarter]=useState(0);const visible=filter==='All'?people:people.filter(p=>p.relationship===filter);return <div className="page"><section className="starter"><div><span className="pill"><Menu/> CONVERSATION STARTER</span><h2>“{starters[starter]}”</h2><p>Curiosity is one of the kindest forms of attention.</p></div><button className="secondary" onClick={()=>setStarter((starter+1)%starters.length)}><RotateCcw/> Another question</button></section><div className="chips"><button className={filter==='All'?'selected':''} onClick={()=>setFilter('All')}>All</button>{[...new Set(people.map(p=>p.relationship))].map(x=><button className={filter===x?'selected':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>{visible.length?<div className="ideas-grid">{visible.flatMap(p=>suggestionBank[p.relationship].map((idea,i)=><article className="idea-card" key={p.id+i}><div className="idea-person"><Avatar person={p} size="sm"/><span>For {p.name}</span></div><Lightbulb/><h3>{idea}</h3><button className="text-button" onClick={()=>remind(idea,p.id)}>Turn into a reminder <ChevronRight/></button></article>))}</div>:<Empty icon={Lightbulb} title="Ideas need a person" copy="Add someone to receive suggestions tailored to your relationship."/>}</div>}
function Reminders({reminders,people,toggle,remove,edit,add}){const [view,setView]=useState('Upcoming');const list=[...reminders].filter(r=>view==='Completed'?r.done:!r.done).sort((a,b)=>a.date.localeCompare(b.date));return <div className="page"><div className="tabs"><button className={view==='Upcoming'?'active':''} onClick={()=>setView('Upcoming')}>Upcoming</button><button className={view==='Completed'?'active':''} onClick={()=>setView('Completed')}>Completed</button></div><section className="panel reminder-list">{list.length?list.map(r=><ReminderRow key={r.id} r={r} person={people.find(p=>p.id===r.personId)} toggle={toggle} remove={remove} edit={edit}/>):<Empty icon={view==='Completed'?Check:Bell} title={view==='Completed'?'No completed nudges yet':'Nothing on your list'} copy={view==='Completed'?'Complete a reminder and your kind moments will appear here.':'Give your future self a gentle prompt.'} action={view==='Upcoming'&&add} label="Create reminder"/>}</section></div>}
function Settings({data,setData,notify,exportData,importRef,importData}){return <div className="page settings-page"><section className="panel setting-section"><div className="section-head"><div><p className="eyebrow">PERSONALIZE</p><h2>Appearance & profile</h2></div></div><label className="setting-row"><span className="setting-icon"><UserRound/></span><span><strong>Your first name</strong><small>Used in your welcome message</small></span><input className="name-input" value={data.firstName} maxLength="30" onChange={e=>setData(d=>({...d,firstName:e.target.value||'Friend'}))}/></label><div className="setting-row"><span className="setting-icon"><Moon/></span><span><strong>Dark mode</strong><small>Use a softer palette after dark</small></span><button role="switch" aria-checked={data.dark} className={`switch ${data.dark?'on':''}`} onClick={()=>setData(d=>({...d,dark:!d.dark}))}><span/></button></div></section><section className="panel setting-section"><div className="section-head"><div><p className="eyebrow">GENTLE PROMPTS</p><h2>Notifications</h2></div></div><div className="setting-row"><span className="setting-icon"><Bell/></span><span><strong>Browser notifications</strong><small>Get reminders while NudgeAI is open</small></span><button className="secondary" onClick={notify}>{data.notifications?'Enabled':'Enable'}</button></div></section><section className="panel setting-section"><div className="section-head"><div><p className="eyebrow">YOUR DATA</p><h2>Backup & restore</h2></div></div><p className="privacy">Your information stays on this device. Export a backup before clearing browser data or moving devices.</p><div className="data-actions"><button className="secondary" onClick={exportData}><Download/> Export JSON</button><button className="secondary" onClick={()=>importRef.current.click()}><Import/> Import JSON</button><input ref={importRef} type="file" accept="application/json" hidden onChange={importData}/><button className="danger-button" onClick={()=>{if(confirm('Reset all NudgeAI data? This cannot be undone.'))setData({...initial,people:[],reminders:[]})}}><Trash2/> Reset everything</button></div></section><footer>Made for the relationships that make life meaningful. <Heart fill="currentColor"/></footer></div>}
